### ISSUE TITLE
Missing file in pkg/snippets folder with wasm-bindgen upgrade

### ISSUE THREAD

**Issue by soonum** [RReverser/wasm-bindgen-rayon#17] opened 2024-10-17 14:56 UTC
Hello, 

When I use wasm-bindgen-rayon `v1.2.2` along with wasm-bindgen `>= v0.2.94`, the `pkg/snippets `  is not fully populated comparing to run with wasm-bindgen `v0.2.93`.

### To reproduce

- clone [zama-ai/tfhe-rs](https://github.com/zama-ai/tfhe-rs) repository
- run `make build_web_js_api_parallel` and check content of `tfhe/pkg/snippets/wasm-bindgen-rayon-<hash>/src`
- change version constraint for wasm-bindgen to `0.2.95`
- remove tfhe/pkg folder
- run again `make build_web_js_api_parallel` and check content of `tfhe/pkg/snippets/wasm-bindgen-rayon-<hash>/src` -> you'll see that `workerHelpers.worker.js` file is missing

**Comment by s-herbert** [comment] 2024-10-31 08:02
I am experiencing this issue as well on personal project - seems problem is around import.meta.url but not quite certain on root cause.

**Comment by codeart1st** [comment] 2024-11-26 05:06
https://github.com/rustwasm/wasm-pack/pull/1443

**Comment by IceTDrinker** [comment] 2024-11-26 15:58
> [rustwasm/wasm-pack#1443](https://github.com/rustwasm/wasm-pack/pull/1443)

Hey @codeart1st does that mean that by changing parameters in a config we will be able to generate the wasm bindgen rayon package as before ?

**Comment by RReverser** [comment] 2024-12-18 18:18
Unfortunately, I'm aware of this issue and did flag it being a breaking change on the original issue: https://github.com/rustwasm/wasm-bindgen/issues/3330

The corresponding PR was merged regardless, which is a really unfortunate breakage of the semver convention.

I hope they'll revert the patch, but it's not looking promising given how the original discussion went.

**Comment by IceTDrinker** [comment] 2024-12-19 15:10
> I have added a workaround to the tip of Git, which is switching back to old, suboptimal, approach for Workers, but at least should work, according to the CI.
> 
> @soonum @zdimension @s-herbert @codeart1st Can you test with your project to see if it does work with latest wasm-pack for you?

Maybe this could help as shared by codeartist

https://github.com/RReverser/wasm-bindgen-rayon/issues/17#issuecomment-2499670374

?

**Comment by RReverser** [comment] 2024-12-19 18:40
Well we can't invoke that from wasm-pack or from the library side, so not really.

**Comment by RReverser** [comment] 2024-12-19 20:21
Slightly worse code splitting, so can impact initialization time a bit, but that's relatively imperceptible.

The worse issue is that it used to break hard in some bundlers (eg Parcel), failing at compile time, but now that the new approach is broken everywhere, figured might be worth a try. Seems to pass on the CI nowadays, but personal feedback would be welcome before I make a release.

**Comment by IceTDrinker** [comment] 2024-12-19 21:57
I would maybe do a release forcing old wasm bindgen version, so that the old system can work on a specific version of wasm bindgen rayon out of the box, as for the « new » system if it’s not breaking a minor, otherwise a major I guess if it breaks something

**Comment by RReverser** [comment] 2024-12-19 22:54
I'm going to wait for feedback for now - couple of days aren't going to change anything. I'd rather issue a fix without pinning if it does work.

**Comment by codeart1st** [comment] 2024-12-20 05:42
> > I have added a workaround to the tip of Git, which is switching back to old, suboptimal, approach for Workers, but at least should work, according to the CI.
> > @soonum @zdimension @s-herbert @codeart1st Can you test with your project to see if it does work with latest wasm-pack for you?
> 
> Maybe this could help as shared by codeartist
> 
> > [rustwasm/wasm-pack#1443](https://github.com/rustwasm/wasm-pack/pull/1443)
> 
> ?

This will only help, if wasm-pack released a new version. Then propably you can invoke `wasm-pack build --split-linked-module` command to get wasm-bindgen-rayon@1.2.2 working.

I will try to test the latest main commit from wasm-bindgen-rayon with the old approach in my project.

**Comment by codeart1st** [comment] 2024-12-20 15:10
Worked for me after upgrading wasm-bindgen to 0.2.99

```
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.46"
wasm-bindgen-rayon = { git = "https://github.com/RReverser/wasm-bindgen-rayon" }
```

![Screenshot From 2024-12-20 16-10-12](https://github.com/user-attachments/assets/ee66e1a0-2f43-4605-a85a-09057dcd5391)

**Comment by RReverser** [comment] 2024-12-20 15:20
@codeart1st as a data point, can you share what bundler you are using?

**Comment by RReverser** [comment] 2024-12-21 19:30
Ok I published this workaround with wasm-bindgen bump as 1.3.0, hopefully this fixes the issue for now.

**Closed by RReverser** 2024-12-21 19:30 UTC

**Comment by codeart1st** [comment] 2024-12-29 07:10
> @codeart1st as a data point, can you share what bundler you are using?

vite@6
