### ISSUE TITLE
Problem using wasm-bindgen-rayon in wasm-bindgen-test

### ISSUE THREAD

**Issue by yuroitaki** [RReverser/wasm-bindgen-rayon#6] opened 2024-04-13 18:51 UTC
Related to https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/issues/30, I tried to initalise thread pool in my wasm bindgen test with the following:

```rust
use wasm_bindgen_futures::{spawn_local, JsFuture};
use wasm_bindgen::prelude::*;
use wasm_bindgen_test::*;

wasm_bindgen_test_configure!(run_in_browser);

#[wasm_bindgen_test]
async fn test() {
   spawn_local(JsFuture::from(init_thread_pool(8)).map(|_| ()));
   ...
}
```

and run the test with the following
```bash
wasm-pack test --firefox --release
```

but the webworkers don't seem to have been set up correctly (picture below) and my test just hang halfway — if i disable rayon in my code, the test will work

<img width="942" alt="image" src="https://github.com/RReverser/wasm-bindgen-rayon/assets/25913766/31097935-0bb7-496f-930c-539928567129">

**Comment by themighty1** [comment] 2024-06-10 06:13
Since initThreadPool should be called from within the WebWorker, I'd expect this to work
```
wasm_bindgen_test_configure!(run_in_dedicated_worker);`

#[wasm_bindgen_test]
async fn test() {
   spawn_local(JsFuture::from(init_thread_pool(8)).map(|_| ()));
   ...
}
```

But even with the above change, my test hang.
I worked around it by modifying the JS code produces by wasm-bindgen-test:
- add `await initThreadPool(navigator.hardwareConcurrency);` right after the wasm was initialized. i.e. to this line https://github.com/rustwasm/wasm-bindgen/blob/c108c7520a13fa124038b28db6fb759b35576dd4/crates/cli/src/bin/wasm-bindgen-test-runner/server.rs#L108
- also add `initThreadPool,` to the imports in that file
- use the patched  `wasm-bindgen-test-runner` instead of the system's default one

**Comment by RReverser** [comment] 2024-12-21 20:17
> spawn_local(JsFuture::from(init_thread_pool(8)).map(|_| ()));

`spawn_local` schedules a future to run in background at later, undetermined point in time. You need to `.await` it instead to make sure that the pool is ready by the time you try to invoke parallel operations.

So this works as expected:

```rust
wasm_bindgen_futures::JsFuture::from(init_thread_pool(8)).await.unwrap();
assert_eq!([1, 2, 3, 4, 5, 6, 7, 8].par_iter().sum::<i32>(), 36);
```

If you have lots of tests, make sure to initialize threadpool only once though.

**Comment by RReverser** [comment] 2024-12-21 20:21
Closing this for now as I don't think there's anything actionable left, but if someone wants to PR a better testing integration, you're welcome to do so.

**Closed by RReverser** 2024-12-21 20:21 UTC

**Comment by vinhtc27** [comment] 2025-04-18 02:24
> So this works as expected:
> 
> wasm_bindgen_futures::JsFuture::from(init_thread_pool(8)).await.unwrap();
> assert_eq!([1, 2, 3, 4, 5, 6, 7, 8].par_iter().sum::<i32>(), 36);
> If you have lots of tests, make sure to initialize threadpool only once though.

Can you please take a look at what the problem is?  @RReverser 
Here is my implementation:  
https://github.com/vacp2p/zerokit/blob/38c18a635222eb905aa2bf0fe36d7711127e7523/rln-wasm/tests/multithread.rs#L275

I tried to use the `init_thread_pool` function exported from my lib in a `wasm-bindgen-test`, but it freezes at:

```rust
JsFuture::from(init_thread_pool(cpu_count)).await
```
And my CPU usage spikes to 100% across all cores.

This is already works normally when I use it with JS in my test using [HTML file](https://github.com/vacp2p/zerokit/blob/38c18a635222eb905aa2bf0fe36d7711127e7523/rln-wasm/benches/index.html#L293) but not in `wasm-bindgen-test`.

I also tried commenting out the following line from my lib:

```rust
pub use wasm_bindgen_rayon::init_thread_pool;
```

And calling `wasm_bindgen_rayon::init_thread_pool` directly in the test, but it still hangs halfway. 
The only difference is that the CPU doesn't max out — the program just becomes unresponsive.


I’ve also tested it using both the `run_in_dedicated_worker` and `run_in_browser` options for `wasm_bindgen_test_configure!` but I got the same result as before in both cases.

**Comment by vinhtc27** [comment] 2025-04-22 06:00
@RReverser 

I was using `wasm-bindgen-rayon` version 1.2.0 for the implementation above.

I tried this example ([issue comment](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/issues/30#issue-1305730459)) with all dependencies updated to their latest versions. 
However, the latest version 1.3.0 still shows the same behavior when used with `wasm-bindgen-test`.
